channels:
  - http://ssb.stsci.edu/astroconda-dev
  - defaults
  
dependencies:
  - python>=3
  - setuptools
  - numpy
  - cython
  - matplotlib
  - d2to1
  - scipy
  - gwcs
  - photutils
  - crds
  - dask
  - stsci.distutils
  - drizzle
  - drizzlepac
  - jwst_lib
  - sphinx_rtd_theme
  - pip:
    - -e git+https://github.com/astropy/astropy.git#egg=astropy
    - -e git+https://github.com/spacetelescope/asdf.git#egg=asdf
    - sphinx-automodapi
